version: '3'

networks:
  easycar:
    driver: ${NETWORKS_DRIVER}

services:
  easycar:
    image: wuqinqiang/easycar:0.0.2
    ports:
      - "8087:8087"
      - "8089:8089"
    depends_on:
      - mysql

  ### MySQL ################################################
  mysql:
    build:
      context: ./init/mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - easycar
  mongodb:
    image: mongo:${MONGODB_VERSION}
    container_name: easycar_mongodb
    #  restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongodb/data/db:/data/db
      - ${DATA_PATH_HOST}/mongodb/data/configdb:/data/configdb
    networks:
      - easycar

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.19
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
    networks:
      - easycar