// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.13.0
// source: easycar.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_CODE_SUCCESS Code = 0
	Code_CODE_FAILED  Code = 1
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "CODE_SUCCESS",
		1: "CODE_FAILED",
	}
	Code_value = map[string]int32{
		"CODE_SUCCESS": 0,
		"CODE_FAILED":  1,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_easycar_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_easycar_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{0}
}

// todo more
type TransactionName int32

const (
	TransactionName_DEFAULT TransactionName = 0
	TransactionName_TCC     TransactionName = 1
	TransactionName_SAGA    TransactionName = 2
)

// Enum value maps for TransactionName.
var (
	TransactionName_name = map[int32]string{
		0: "DEFAULT",
		1: "TCC",
		2: "SAGA",
	}
	TransactionName_value = map[string]int32{
		"DEFAULT": 0,
		"TCC":     1,
		"SAGA":    2,
	}
)

func (x TransactionName) Enum() *TransactionName {
	p := new(TransactionName)
	*p = x
	return p
}

func (x TransactionName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionName) Descriptor() protoreflect.EnumDescriptor {
	return file_easycar_proto_enumTypes[1].Descriptor()
}

func (TransactionName) Type() protoreflect.EnumType {
	return &file_easycar_proto_enumTypes[1]
}

func (x TransactionName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionName.Descriptor instead.
func (TransactionName) EnumDescriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{1}
}

//todo more
type GlobalState int32

const (
	GlobalState_GLOBAL_DEFAULT GlobalState = 0
	GlobalState_PREPARED       GlobalState = 1
	GlobalState_SUBMITTED      GlobalState = 2
	GlobalState_SUCCEED        GlobalState = 3
	GlobalState_FAILED         GlobalState = 4
	GlobalState_ABORT          GlobalState = 5
)

// Enum value maps for GlobalState.
var (
	GlobalState_name = map[int32]string{
		0: "GLOBAL_DEFAULT",
		1: "PREPARED",
		2: "SUBMITTED",
		3: "SUCCEED",
		4: "FAILED",
		5: "ABORT",
	}
	GlobalState_value = map[string]int32{
		"GLOBAL_DEFAULT": 0,
		"PREPARED":       1,
		"SUBMITTED":      2,
		"SUCCEED":        3,
		"FAILED":         4,
		"ABORT":          5,
	}
)

func (x GlobalState) Enum() *GlobalState {
	p := new(GlobalState)
	*p = x
	return p
}

func (x GlobalState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalState) Descriptor() protoreflect.EnumDescriptor {
	return file_easycar_proto_enumTypes[2].Descriptor()
}

func (GlobalState) Type() protoreflect.EnumType {
	return &file_easycar_proto_enumTypes[2]
}

func (x GlobalState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalState.Descriptor instead.
func (GlobalState) EnumDescriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{2}
}

//todo more
type BranchState int32

const (
	BranchState_BRANCH_DEFAULT BranchState = 0
	BranchState_BRANCH_READY   BranchState = 1
	BranchState_BRANCH_SUCCEED BranchState = 2
	BranchState_BRANCH_FAILED  BranchState = 3
)

// Enum value maps for BranchState.
var (
	BranchState_name = map[int32]string{
		0: "BRANCH_DEFAULT",
		1: "BRANCH_READY",
		2: "BRANCH_SUCCEED",
		3: "BRANCH_FAILED",
	}
	BranchState_value = map[string]int32{
		"BRANCH_DEFAULT": 0,
		"BRANCH_READY":   1,
		"BRANCH_SUCCEED": 2,
		"BRANCH_FAILED":  3,
	}
)

func (x BranchState) Enum() *BranchState {
	p := new(BranchState)
	*p = x
	return p
}

func (x BranchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BranchState) Descriptor() protoreflect.EnumDescriptor {
	return file_easycar_proto_enumTypes[3].Descriptor()
}

func (BranchState) Type() protoreflect.EnumType {
	return &file_easycar_proto_enumTypes[3]
}

func (x BranchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BranchState.Descriptor instead.
func (BranchState) EnumDescriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{3}
}

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=code,proto3,enum=apis.Code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_SUCCESS
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BeginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name TransactionName `protobuf:"varint,1,opt,name=name,proto3,enum=apis.TransactionName" json:"name,omitempty"`
}

func (x *BeginReq) Reset() {
	*x = BeginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginReq) ProtoMessage() {}

func (x *BeginReq) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginReq.ProtoReflect.Descriptor instead.
func (*BeginReq) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{1}
}

func (x *BeginReq) GetName() TransactionName {
	if x != nil {
		return x.Name
	}
	return TransactionName_DEFAULT
}

type BeginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp      `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   *BeginRespInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BeginResp) Reset() {
	*x = BeginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResp) ProtoMessage() {}

func (x *BeginResp) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResp.ProtoReflect.Descriptor instead.
func (*BeginResp) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{2}
}

func (x *BeginResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *BeginResp) GetData() *BeginRespInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GId string `protobuf:"bytes,1,opt,name=GId,proto3" json:"GId,omitempty"`
}

func (x *CommitReq) Reset() {
	*x = CommitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReq) ProtoMessage() {}

func (x *CommitReq) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReq.ProtoReflect.Descriptor instead.
func (*CommitReq) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{3}
}

func (x *CommitReq) GetGId() string {
	if x != nil {
		return x.GId
	}
	return ""
}

type CommitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp       `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   *CommitRespInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CommitResp) Reset() {
	*x = CommitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResp) ProtoMessage() {}

func (x *CommitResp) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResp.ProtoReflect.Descriptor instead.
func (*CommitResp) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{4}
}

func (x *CommitResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *CommitResp) GetData() *CommitRespInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type RollBackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GId string `protobuf:"bytes,1,opt,name=GId,proto3" json:"GId,omitempty"`
}

func (x *RollBackReq) Reset() {
	*x = RollBackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollBackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollBackReq) ProtoMessage() {}

func (x *RollBackReq) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollBackReq.ProtoReflect.Descriptor instead.
func (*RollBackReq) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{5}
}

func (x *RollBackReq) GetGId() string {
	if x != nil {
		return x.GId
	}
	return ""
}

type RollBackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp         `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   *RollBackRespInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RollBackResp) Reset() {
	*x = RollBackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollBackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollBackResp) ProtoMessage() {}

func (x *RollBackResp) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollBackResp.ProtoReflect.Descriptor instead.
func (*RollBackResp) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{6}
}

func (x *RollBackResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *RollBackResp) GetData() *RollBackRespInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type BeginRespInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GId string `protobuf:"bytes,1,opt,name=GId,proto3" json:"GId,omitempty"`
}

func (x *BeginRespInfo) Reset() {
	*x = BeginRespInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginRespInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRespInfo) ProtoMessage() {}

func (x *BeginRespInfo) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRespInfo.ProtoReflect.Descriptor instead.
func (*BeginRespInfo) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BeginRespInfo) GetGId() string {
	if x != nil {
		return x.GId
	}
	return ""
}

type CommitRespInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State GlobalState `protobuf:"varint,1,opt,name=state,proto3,enum=apis.GlobalState" json:"state,omitempty"`
}

func (x *CommitRespInfo) Reset() {
	*x = CommitRespInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitRespInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRespInfo) ProtoMessage() {}

func (x *CommitRespInfo) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRespInfo.ProtoReflect.Descriptor instead.
func (*CommitRespInfo) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CommitRespInfo) GetState() GlobalState {
	if x != nil {
		return x.State
	}
	return GlobalState_GLOBAL_DEFAULT
}

type RollBackRespInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State GlobalState `protobuf:"varint,1,opt,name=state,proto3,enum=apis.GlobalState" json:"state,omitempty"`
}

func (x *RollBackRespInfo) Reset() {
	*x = RollBackRespInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_easycar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollBackRespInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollBackRespInfo) ProtoMessage() {}

func (x *RollBackRespInfo) ProtoReflect() protoreflect.Message {
	mi := &file_easycar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollBackRespInfo.ProtoReflect.Descriptor instead.
func (*RollBackRespInfo) Descriptor() ([]byte, []int) {
	return file_easycar_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RollBackRespInfo) GetState() GlobalState {
	if x != nil {
		return x.State
	}
	return GlobalState_GLOBAL_DEFAULT
}

var File_easycar_proto protoreflect.FileDescriptor

var file_easycar_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x61, 0x73, 0x79, 0x63, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x61, 0x70, 0x69, 0x73, 0x22, 0x3c, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x35, 0x0a, 0x08, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x29, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x77, 0x0a, 0x09, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x69,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x18, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x47, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47,
	0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x70,
	0x69, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x47, 0x49, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x6c, 0x42,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2f, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x29, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x44, 0x45, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x2a, 0x31, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x43, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x41, 0x47, 0x41, 0x10, 0x02, 0x2a, 0x62, 0x0a, 0x0b, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x4c,
	0x4f, 0x42, 0x41, 0x4c, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x55, 0x42, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x10, 0x05, 0x2a,
	0x5a, 0x0a, 0x0b, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x0e, 0x42, 0x52, 0x41, 0x4e, 0x43, 0x48, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x52, 0x41, 0x4e, 0x43, 0x48, 0x5f, 0x52, 0x45, 0x41,
	0x44, 0x59, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x52, 0x41, 0x4e, 0x43, 0x48, 0x5f, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x52, 0x41, 0x4e,
	0x43, 0x48, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x32, 0x98, 0x01, 0x0a, 0x07,
	0x45, 0x61, 0x73, 0x79, 0x43, 0x61, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x0f, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x11,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x75, 0x71, 0x69, 0x6e, 0x71, 0x69, 0x61, 0x6e, 0x67, 0x2f,
	0x65, 0x61, 0x73, 0x79, 0x63, 0x61, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_easycar_proto_rawDescOnce sync.Once
	file_easycar_proto_rawDescData = file_easycar_proto_rawDesc
)

func file_easycar_proto_rawDescGZIP() []byte {
	file_easycar_proto_rawDescOnce.Do(func() {
		file_easycar_proto_rawDescData = protoimpl.X.CompressGZIP(file_easycar_proto_rawDescData)
	})
	return file_easycar_proto_rawDescData
}

var file_easycar_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_easycar_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_easycar_proto_goTypes = []interface{}{
	(Code)(0),                // 0: apis.Code
	(TransactionName)(0),     // 1: apis.TransactionName
	(GlobalState)(0),         // 2: apis.GlobalState
	(BranchState)(0),         // 3: apis.BranchState
	(*BaseResp)(nil),         // 4: apis.BaseResp
	(*BeginReq)(nil),         // 5: apis.BeginReq
	(*BeginResp)(nil),        // 6: apis.BeginResp
	(*CommitReq)(nil),        // 7: apis.CommitReq
	(*CommitResp)(nil),       // 8: apis.CommitResp
	(*RollBackReq)(nil),      // 9: apis.RollBackReq
	(*RollBackResp)(nil),     // 10: apis.RollBackResp
	(*BeginRespInfo)(nil),    // 11: apis.BeginResp.info
	(*CommitRespInfo)(nil),   // 12: apis.CommitResp.info
	(*RollBackRespInfo)(nil), // 13: apis.RollBackResp.info
}
var file_easycar_proto_depIdxs = []int32{
	0,  // 0: apis.BaseResp.code:type_name -> apis.Code
	1,  // 1: apis.BeginReq.name:type_name -> apis.TransactionName
	4,  // 2: apis.BeginResp.common:type_name -> apis.BaseResp
	11, // 3: apis.BeginResp.data:type_name -> apis.BeginResp.info
	4,  // 4: apis.CommitResp.common:type_name -> apis.BaseResp
	12, // 5: apis.CommitResp.data:type_name -> apis.CommitResp.info
	4,  // 6: apis.RollBackResp.common:type_name -> apis.BaseResp
	13, // 7: apis.RollBackResp.data:type_name -> apis.RollBackResp.info
	2,  // 8: apis.CommitResp.info.state:type_name -> apis.GlobalState
	2,  // 9: apis.RollBackResp.info.state:type_name -> apis.GlobalState
	5,  // 10: apis.EasyCar.Begin:input_type -> apis.BeginReq
	7,  // 11: apis.EasyCar.Commit:input_type -> apis.CommitReq
	9,  // 12: apis.EasyCar.RollBack:input_type -> apis.RollBackReq
	6,  // 13: apis.EasyCar.Begin:output_type -> apis.BeginResp
	8,  // 14: apis.EasyCar.Commit:output_type -> apis.CommitResp
	9,  // 15: apis.EasyCar.RollBack:output_type -> apis.RollBackReq
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_easycar_proto_init() }
func file_easycar_proto_init() {
	if File_easycar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_easycar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollBackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollBackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginRespInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitRespInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_easycar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollBackRespInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_easycar_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_easycar_proto_goTypes,
		DependencyIndexes: file_easycar_proto_depIdxs,
		EnumInfos:         file_easycar_proto_enumTypes,
		MessageInfos:      file_easycar_proto_msgTypes,
	}.Build()
	File_easycar_proto = out.File
	file_easycar_proto_rawDesc = nil
	file_easycar_proto_goTypes = nil
	file_easycar_proto_depIdxs = nil
}
