// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBranch = "branch"

// Branch mapped from table <branch>
type Branch struct {
	ID       int32  `gorm:"column:id;type:int;primaryKey" json:"id"`
	GID      string `gorm:"column:g_id;type:varchar(255);not null" json:"g_id"`
	BranchID string `gorm:"column:branch_id;type:varchar(255);not null" json:"branch_id"`
	URL      string `gorm:"column:url;type:varchar(255);not null" json:"url"`
	ReqData  string `gorm:"column:req_data;type:varchar(255);not null" json:"req_data"`
	TranType string `gorm:"column:tran_type;type:varchar(255);not null" json:"tran_type"`
	PID      string `gorm:"column:p_id;type:varchar(255);not null" json:"p_id"`
	Protocol string `gorm:"column:protocol;type:varchar(255);not null" json:"protocol"`
	Action   string `gorm:"column:action;type:varchar(255);not null" json:"action"`
	State    string `gorm:"column:state;type:varchar(255);not null" json:"state"`
	EndTime  int32  `gorm:"column:end_time;type:int;not null;default:0" json:"end_time"`
	Level    int32  `gorm:"column:level;type:int;not null;default:1" json:"level"`
}

// TableName Branch's table name
func (*Branch) TableName() string {
	return TableNameBranch
}
