// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGlobal = "global"

// Global mapped from table <global>
type Global struct {
	ID           int32  `gorm:"column:id;type:int;primaryKey" json:"id"`
	GID          string `gorm:"column:g_id;type:varchar(255);not null" json:"g_id"`
	State        string `gorm:"column:state;type:varchar(255);not null;default:begin" json:"state"`
	EndTime      int32  `gorm:"column:end_time;type:int;not null;default:0" json:"end_time"`
	NextCronTime int32  `gorm:"column:next_cron_time;type:int;not null;default:0" json:"next_cron_time"`
}

// TableName Global's table name
func (*Global) TableName() string {
	return TableNameGlobal
}
