// Code generated by protoc-gen-go-coordinator. DO NOT EDIT.
// versions:
// - protoc-gen-go-coordinator v1.2.0
// - protoc             v3.21.2
// source: proto/easycar.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EasyCarClient is the client API for EasyCar services.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EasyCarClient interface {
	Begin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BeginResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Commit(ctx context.Context, in *CommitReq, opts ...grpc.CallOption) (*CommitResp, error)
	Abort(ctx context.Context, in *AbortReq, opts ...grpc.CallOption) (*AbortResp, error)
	GetState(ctx context.Context, in *GetStateReq, opts ...grpc.CallOption) (*GetStateResp, error)
}

type easyCarClient struct {
	cc grpc.ClientConnInterface
}

func NewEasyCarClient(cc grpc.ClientConnInterface) EasyCarClient {
	return &easyCarClient{cc}
}

func (c *easyCarClient) Begin(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BeginResp, error) {
	out := new(BeginResp)
	err := c.cc.Invoke(ctx, "/proto.EasyCar/Begin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easyCarClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/proto.EasyCar/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easyCarClient) Commit(ctx context.Context, in *CommitReq, opts ...grpc.CallOption) (*CommitResp, error) {
	out := new(CommitResp)
	err := c.cc.Invoke(ctx, "/proto.EasyCar/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easyCarClient) Abort(ctx context.Context, in *AbortReq, opts ...grpc.CallOption) (*AbortResp, error) {
	out := new(AbortResp)
	err := c.cc.Invoke(ctx, "/proto.EasyCar/Abort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easyCarClient) GetState(ctx context.Context, in *GetStateReq, opts ...grpc.CallOption) (*GetStateResp, error) {
	out := new(GetStateResp)
	err := c.cc.Invoke(ctx, "/proto.EasyCar/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EasyCarServer is the server API for EasyCar services.
// All implementations must embed UnimplementedEasyCarServer
// for forward compatibility
type EasyCarServer interface {
	Begin(context.Context, *emptypb.Empty) (*BeginResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Commit(context.Context, *CommitReq) (*CommitResp, error)
	Abort(context.Context, *AbortReq) (*AbortResp, error)
	GetState(context.Context, *GetStateReq) (*GetStateResp, error)
	mustEmbedUnimplementedEasyCarServer()
}

// UnimplementedEasyCarServer must be embedded to have forward compatible implementations.
type UnimplementedEasyCarServer struct {
}

func (UnimplementedEasyCarServer) Begin(context.Context, *emptypb.Empty) (*BeginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedEasyCarServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedEasyCarServer) Commit(context.Context, *CommitReq) (*CommitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedEasyCarServer) Abort(context.Context, *AbortReq) (*AbortResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedEasyCarServer) GetState(context.Context, *GetStateReq) (*GetStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedEasyCarServer) mustEmbedUnimplementedEasyCarServer() {}

// UnsafeEasyCarServer may be embedded to opt out of forward compatibility for this services.
// Use of this interface is not recommended, as added methods to EasyCarServer will
// result in compilation errors.
type UnsafeEasyCarServer interface {
	mustEmbedUnimplementedEasyCarServer()
}

func RegisterEasyCarServer(s grpc.ServiceRegistrar, srv EasyCarServer) {
	s.RegisterService(&EasyCar_ServiceDesc, srv)
}

func _EasyCar_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasyCarServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EasyCar/Begin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasyCarServer).Begin(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasyCar_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasyCarServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EasyCar/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasyCarServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasyCar_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasyCarServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EasyCar/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasyCarServer).Commit(ctx, req.(*CommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasyCar_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasyCarServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EasyCar/Abort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasyCarServer).Abort(ctx, req.(*AbortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasyCar_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasyCarServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EasyCar/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasyCarServer).GetState(ctx, req.(*GetStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EasyCar_ServiceDesc is the grpc.ServiceDesc for EasyCar services.
// It's only intended for direct use with coordinator.RegisterService,
// and not to be introspected or modified (even as a copy)
var EasyCar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EasyCar",
	HandlerType: (*EasyCarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _EasyCar_Begin_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _EasyCar_Register_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _EasyCar_Commit_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _EasyCar_Abort_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _EasyCar_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/easycar.proto",
}
