// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: proto/easycar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_CODE_SUCCESS Code = 0
	Code_CODE_FAILED  Code = 1
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "CODE_SUCCESS",
		1: "CODE_FAILED",
	}
	Code_value = map[string]int32{
		"CODE_SUCCESS": 0,
		"CODE_FAILED":  1,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_easycar_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_proto_easycar_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{0}
}

// todo more
type TransactionName int32

const (
	TransactionName_DEFAULT TransactionName = 0
	TransactionName_TCC     TransactionName = 1
	TransactionName_SAGA    TransactionName = 2
)

// Enum value maps for TransactionName.
var (
	TransactionName_name = map[int32]string{
		0: "DEFAULT",
		1: "TCC",
		2: "SAGA",
	}
	TransactionName_value = map[string]int32{
		"DEFAULT": 0,
		"TCC":     1,
		"SAGA":    2,
	}
)

func (x TransactionName) Enum() *TransactionName {
	p := new(TransactionName)
	*p = x
	return p
}

func (x TransactionName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionName) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_easycar_proto_enumTypes[1].Descriptor()
}

func (TransactionName) Type() protoreflect.EnumType {
	return &file_proto_easycar_proto_enumTypes[1]
}

func (x TransactionName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionName.Descriptor instead.
func (TransactionName) EnumDescriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{1}
}

//todo more
type GlobalState int32

const (
	GlobalState_GLOBAL_DEFAULT GlobalState = 0
	GlobalState_PREPARED       GlobalState = 1
	GlobalState_SUBMITTED      GlobalState = 2
	GlobalState_SUCCEED        GlobalState = 3
	GlobalState_FAILED         GlobalState = 4
	GlobalState_ABORT          GlobalState = 5
)

// Enum value maps for GlobalState.
var (
	GlobalState_name = map[int32]string{
		0: "GLOBAL_DEFAULT",
		1: "PREPARED",
		2: "SUBMITTED",
		3: "SUCCEED",
		4: "FAILED",
		5: "ABORT",
	}
	GlobalState_value = map[string]int32{
		"GLOBAL_DEFAULT": 0,
		"PREPARED":       1,
		"SUBMITTED":      2,
		"SUCCEED":        3,
		"FAILED":         4,
		"ABORT":          5,
	}
)

func (x GlobalState) Enum() *GlobalState {
	p := new(GlobalState)
	*p = x
	return p
}

func (x GlobalState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_easycar_proto_enumTypes[2].Descriptor()
}

func (GlobalState) Type() protoreflect.EnumType {
	return &file_proto_easycar_proto_enumTypes[2]
}

func (x GlobalState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalState.Descriptor instead.
func (GlobalState) EnumDescriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{2}
}

//todo more
type BranchState int32

const (
	BranchState_BRANCH_DEFAULT BranchState = 0
	BranchState_BRANCH_READY   BranchState = 1
	BranchState_BRANCH_SUCCEED BranchState = 2
	BranchState_BRANCH_FAILED  BranchState = 3
)

// Enum value maps for BranchState.
var (
	BranchState_name = map[int32]string{
		0: "BRANCH_DEFAULT",
		1: "BRANCH_READY",
		2: "BRANCH_SUCCEED",
		3: "BRANCH_FAILED",
	}
	BranchState_value = map[string]int32{
		"BRANCH_DEFAULT": 0,
		"BRANCH_READY":   1,
		"BRANCH_SUCCEED": 2,
		"BRANCH_FAILED":  3,
	}
)

func (x BranchState) Enum() *BranchState {
	p := new(BranchState)
	*p = x
	return p
}

func (x BranchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BranchState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_easycar_proto_enumTypes[3].Descriptor()
}

func (BranchState) Type() protoreflect.EnumType {
	return &file_proto_easycar_proto_enumTypes[3]
}

func (x BranchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BranchState.Descriptor instead.
func (BranchState) EnumDescriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{3}
}

type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{0}
}

type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_SUCCESS
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BeginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name TransactionName `protobuf:"varint,1,opt,name=name,proto3,enum=proto.TransactionName" json:"name,omitempty"`
}

func (x *BeginReq) Reset() {
	*x = BeginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginReq) ProtoMessage() {}

func (x *BeginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginReq.ProtoReflect.Descriptor instead.
func (*BeginReq) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{3}
}

func (x *BeginReq) GetName() TransactionName {
	if x != nil {
		return x.Name
	}
	return TransactionName_DEFAULT
}

type BeginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp      `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   *BeginRespInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BeginResp) Reset() {
	*x = BeginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResp) ProtoMessage() {}

func (x *BeginResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResp.ProtoReflect.Descriptor instead.
func (*BeginResp) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{4}
}

func (x *BeginResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *BeginResp) GetData() *BeginRespInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GId string `protobuf:"bytes,1,opt,name=GId,proto3" json:"GId,omitempty"`
}

func (x *CommitReq) Reset() {
	*x = CommitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReq) ProtoMessage() {}

func (x *CommitReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReq.ProtoReflect.Descriptor instead.
func (*CommitReq) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{5}
}

func (x *CommitReq) GetGId() string {
	if x != nil {
		return x.GId
	}
	return ""
}

type CommitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp       `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   *CommitRespInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CommitResp) Reset() {
	*x = CommitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResp) ProtoMessage() {}

func (x *CommitResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResp.ProtoReflect.Descriptor instead.
func (*CommitResp) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{6}
}

func (x *CommitResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *CommitResp) GetData() *CommitRespInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type AbortReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GId string `protobuf:"bytes,1,opt,name=GId,proto3" json:"GId,omitempty"`
}

func (x *AbortReq) Reset() {
	*x = AbortReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortReq) ProtoMessage() {}

func (x *AbortReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortReq.ProtoReflect.Descriptor instead.
func (*AbortReq) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{7}
}

func (x *AbortReq) GetGId() string {
	if x != nil {
		return x.GId
	}
	return ""
}

type AbortResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *AbortResp) Reset() {
	*x = AbortResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResp) ProtoMessage() {}

func (x *AbortResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResp.ProtoReflect.Descriptor instead.
func (*AbortResp) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{8}
}

func (x *AbortResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

type RollBackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp         `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Data   *RollBackRespInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RollBackResp) Reset() {
	*x = RollBackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollBackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollBackResp) ProtoMessage() {}

func (x *RollBackResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollBackResp.ProtoReflect.Descriptor instead.
func (*RollBackResp) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{9}
}

func (x *RollBackResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *RollBackResp) GetData() *RollBackRespInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GId string `protobuf:"bytes,1,opt,name=GId,proto3" json:"GId,omitempty"`
}

func (x *GetStateReq) Reset() {
	*x = GetStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReq) ProtoMessage() {}

func (x *GetStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReq.ProtoReflect.Descriptor instead.
func (*GetStateReq) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{10}
}

func (x *GetStateReq) GetGId() string {
	if x != nil {
		return x.GId
	}
	return ""
}

type GetStateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *BaseResp `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *GetStateResp) Reset() {
	*x = GetStateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResp) ProtoMessage() {}

func (x *GetStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResp.ProtoReflect.Descriptor instead.
func (*GetStateResp) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{11}
}

func (x *GetStateResp) GetCommon() *BaseResp {
	if x != nil {
		return x.Common
	}
	return nil
}

type BeginRespInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GId string `protobuf:"bytes,1,opt,name=GId,proto3" json:"GId,omitempty"`
}

func (x *BeginRespInfo) Reset() {
	*x = BeginRespInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginRespInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRespInfo) ProtoMessage() {}

func (x *BeginRespInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRespInfo.ProtoReflect.Descriptor instead.
func (*BeginRespInfo) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{4, 0}
}

func (x *BeginRespInfo) GetGId() string {
	if x != nil {
		return x.GId
	}
	return ""
}

type CommitRespInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State GlobalState `protobuf:"varint,1,opt,name=state,proto3,enum=proto.GlobalState" json:"state,omitempty"`
}

func (x *CommitRespInfo) Reset() {
	*x = CommitRespInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitRespInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRespInfo) ProtoMessage() {}

func (x *CommitRespInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRespInfo.ProtoReflect.Descriptor instead.
func (*CommitRespInfo) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CommitRespInfo) GetState() GlobalState {
	if x != nil {
		return x.State
	}
	return GlobalState_GLOBAL_DEFAULT
}

type RollBackRespInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State GlobalState `protobuf:"varint,1,opt,name=state,proto3,enum=proto.GlobalState" json:"state,omitempty"`
}

func (x *RollBackRespInfo) Reset() {
	*x = RollBackRespInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_easycar_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollBackRespInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollBackRespInfo) ProtoMessage() {}

func (x *RollBackRespInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easycar_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollBackRespInfo.ProtoReflect.Descriptor instead.
func (*RollBackRespInfo) Descriptor() ([]byte, []int) {
	return file_proto_easycar_proto_rawDescGZIP(), []int{9, 0}
}

func (x *RollBackRespInfo) GetState() GlobalState {
	if x != nil {
		return x.State
	}
	return GlobalState_GLOBAL_DEFAULT
}

var File_proto_easycar_proto protoreflect.FileDescriptor

var file_proto_easycar_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x61, 0x73, 0x79, 0x63, 0x61, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x37, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x22, 0x3d, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x36, 0x0a, 0x08, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x79, 0x0a, 0x09, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x29,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x69,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x18, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x47, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47,
	0x49, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x69, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x28,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x47, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x09, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a,
	0x0c, 0x52, 0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c,
	0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x47, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2a, 0x29, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x2a, 0x31, 0x0a, 0x0f, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54,
	0x43, 0x43, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x41, 0x47, 0x41, 0x10, 0x02, 0x2a, 0x62,
	0x0a, 0x0b, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x0e, 0x47, 0x4c, 0x4f, 0x42, 0x41, 0x4c, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x53, 0x55, 0x42, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x42, 0x4f, 0x52, 0x54,
	0x10, 0x05, 0x2a, 0x5a, 0x0a, 0x0b, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x52, 0x41, 0x4e, 0x43, 0x48, 0x5f, 0x44, 0x45, 0x46, 0x41,
	0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x52, 0x41, 0x4e, 0x43, 0x48, 0x5f,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x52, 0x41, 0x4e, 0x43,
	0x48, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x42,
	0x52, 0x41, 0x4e, 0x43, 0x48, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x32, 0x8b,
	0x02, 0x0a, 0x07, 0x45, 0x61, 0x73, 0x79, 0x43, 0x61, 0x72, 0x12, 0x33, 0x0a, 0x05, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x35, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x05, 0x41, 0x62, 0x6f, 0x72, 0x74,
	0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_easycar_proto_rawDescOnce sync.Once
	file_proto_easycar_proto_rawDescData = file_proto_easycar_proto_rawDesc
)

func file_proto_easycar_proto_rawDescGZIP() []byte {
	file_proto_easycar_proto_rawDescOnce.Do(func() {
		file_proto_easycar_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_easycar_proto_rawDescData)
	})
	return file_proto_easycar_proto_rawDescData
}

var file_proto_easycar_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_easycar_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_easycar_proto_goTypes = []interface{}{
	(Code)(0),                // 0: proto.Code
	(TransactionName)(0),     // 1: proto.TransactionName
	(GlobalState)(0),         // 2: proto.GlobalState
	(BranchState)(0),         // 3: proto.BranchState
	(*RegisterReq)(nil),      // 4: proto.RegisterReq
	(*RegisterResp)(nil),     // 5: proto.RegisterResp
	(*BaseResp)(nil),         // 6: proto.BaseResp
	(*BeginReq)(nil),         // 7: proto.BeginReq
	(*BeginResp)(nil),        // 8: proto.BeginResp
	(*CommitReq)(nil),        // 9: proto.CommitReq
	(*CommitResp)(nil),       // 10: proto.CommitResp
	(*AbortReq)(nil),         // 11: proto.AbortReq
	(*AbortResp)(nil),        // 12: proto.AbortResp
	(*RollBackResp)(nil),     // 13: proto.RollBackResp
	(*GetStateReq)(nil),      // 14: proto.GetStateReq
	(*GetStateResp)(nil),     // 15: proto.GetStateResp
	(*BeginRespInfo)(nil),    // 16: proto.BeginResp.info
	(*CommitRespInfo)(nil),   // 17: proto.CommitResp.info
	(*RollBackRespInfo)(nil), // 18: proto.RollBackResp.info
	(*emptypb.Empty)(nil),    // 19: google.protobuf.Empty
}
var file_proto_easycar_proto_depIdxs = []int32{
	6,  // 0: proto.RegisterResp.common:type_name -> proto.BaseResp
	0,  // 1: proto.BaseResp.code:type_name -> proto.Code
	1,  // 2: proto.BeginReq.name:type_name -> proto.TransactionName
	6,  // 3: proto.BeginResp.common:type_name -> proto.BaseResp
	16, // 4: proto.BeginResp.data:type_name -> proto.BeginResp.info
	6,  // 5: proto.CommitResp.common:type_name -> proto.BaseResp
	17, // 6: proto.CommitResp.data:type_name -> proto.CommitResp.info
	6,  // 7: proto.AbortResp.common:type_name -> proto.BaseResp
	6,  // 8: proto.RollBackResp.common:type_name -> proto.BaseResp
	18, // 9: proto.RollBackResp.data:type_name -> proto.RollBackResp.info
	6,  // 10: proto.GetStateResp.common:type_name -> proto.BaseResp
	2,  // 11: proto.CommitResp.info.state:type_name -> proto.GlobalState
	2,  // 12: proto.RollBackResp.info.state:type_name -> proto.GlobalState
	19, // 13: proto.EasyCar.Begin:input_type -> google.protobuf.Empty
	4,  // 14: proto.EasyCar.Register:input_type -> proto.RegisterReq
	9,  // 15: proto.EasyCar.Commit:input_type -> proto.CommitReq
	11, // 16: proto.EasyCar.Abort:input_type -> proto.AbortReq
	14, // 17: proto.EasyCar.GetState:input_type -> proto.GetStateReq
	8,  // 18: proto.EasyCar.Begin:output_type -> proto.BeginResp
	5,  // 19: proto.EasyCar.Register:output_type -> proto.RegisterResp
	10, // 20: proto.EasyCar.Commit:output_type -> proto.CommitResp
	12, // 21: proto.EasyCar.Abort:output_type -> proto.AbortResp
	15, // 22: proto.EasyCar.GetState:output_type -> proto.GetStateResp
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_easycar_proto_init() }
func file_proto_easycar_proto_init() {
	if File_proto_easycar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_easycar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollBackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginRespInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitRespInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_easycar_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollBackRespInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_easycar_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_easycar_proto_goTypes,
		DependencyIndexes: file_proto_easycar_proto_depIdxs,
		EnumInfos:         file_proto_easycar_proto_enumTypes,
		MessageInfos:      file_proto_easycar_proto_msgTypes,
	}.Build()
	File_proto_easycar_proto = out.File
	file_proto_easycar_proto_rawDesc = nil
	file_proto_easycar_proto_goTypes = nil
	file_proto_easycar_proto_depIdxs = nil
}
